"""
Django settings for backend project Distributed AI Demo.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

Role in system
--------------
Central configuration for the Django REST API component of the distributed AI pipeline.

Flow position
-------------
Client -> Django REST API -> Kafka -> Consumer -> Celery -> AI Worker -> DB

Responsibilities
---------------
- Configure Django apps
- Configure database connections
- Configure Celery
- Configure Redis
- Configure Kafka settings
- Configure REST API behavior

Used by
-------
- Django server
- Celery workers
- Kafka consumer
- Management commands

Notes
-----
This settings module configures only the API layer.
Distributed processing happens outside Django via Kafka and Celery workers.
"""

from pathlib import Path

# BASE_DIR: root of the backend project.
# Used for relative paths to templates, static files, etc.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
# This key is used for cryptographic signing (sessions, CSRF tokens, etc.).
SECRET_KEY = "django-insecure-0^m&-j-(eapfa@f#a9eyl&wp8*44cyks^((-eqblemye7j6+%9"

# DEBUG mode: True shows detailed error pages; should be False in production.
DEBUG = True

# Hosts allowed to connect; empty for development, must set in production.
# A list of hostnames or IP addresses that Django will accept HTTP requests from.
# Django uses it to prevent HTTP Host header attacks, which are a type of security vulnerability where a request can pretend to be sent to the server from a fake host.
ALLOWED_HOSTS = []

# Installed applications
# ----------------------
# - Django core apps: admin, auth, contenttypes, sessions, messages, staticfiles
# - REST framework: for API endpoints
# - core: custom app containing Kafka producers/consumers and Celery tasks
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "core",
]

# Middleware stack
# ----------------
# Handles requests/responses: security, sessions, CSRF, auth, messages, clickjacking protection.
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Root URL configuration for the project (REST API endpoints).
# The Python module that Django loads to know how to route incoming HTTP requests to the appropriate views.
# 'xxx.urls' refers to the Python module xxx/urls.py.
# In other words, it tells Django where the URL patterns live.
# Django will import this module, and look for a variable called urlpatterns, the list of all URL patterns for the project.
ROOT_URLCONF = "backend.urls"  # 'backend.urls' → <backend/urls.py>.

# Templates configuration
# -----------------------
# A list of template engine configurations.
# Templates are HTML files or other text formats that Django can render and send as HTTP responses.
# Even in case of a REST API that primarily returns JSON, TEMPLATES is still used for:
# - The admin interface (/admin)
# - Any HTML pages you may render in views
# - Error pages (404.html, 500.html)
# Backend: DjangoTemplates
# APP_DIRS: True to load templates from apps (e.g., admin)
# Context processors: request, auth, messages
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",  # The template engine to use — here, Django’s default engine.
        "DIRS": [],  # Additional directories for templates
        "APP_DIRS": True,  # True, so Django will look for templates inside each installed app under the templates/ folder.
        "OPTIONS": {  # Functions that inject variables into all templates automatically.
            "context_processors": [
                "django.template.context_processors.request",  # Adds the request object to templates.
                "django.contrib.auth.context_processors.auth",  # Adds user, perms objects.
                "django.contrib.messages.context_processors.messages",  # Adds messages for the user.
            ],
        },
    },
]

# WSGI entrypoint: used in production deployment to run the API layer.
WSGI_APPLICATION = "backend.wsgi.application"

# Database configuration
# ----------------------
# PostgreSQL: structured storage
# Matches docker-compose credentials
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "demo",
        "USER": "demo",
        "PASSWORD": "demo",
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# Password validators for strong admin credentials
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
# --------------------
LANGUAGE_CODE = "en-us"  # Language for the API / admin interface
TIME_ZONE = "UTC"  # UTC timezone for distributed consistency
USE_I18N = True  # Enable Django internationalization
USE_TZ = True  # Enable timezone-aware datetimes

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"  # URL prefix for static files

# Celery configuration
# -------------------
# Connects Celery to Redis broker.
# Ensures tasks (Kafka -> Celery) are serialized in JSON.
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
